### ISSUE TITLE
Unable to run pocketNC automatically after reboot;

### ISSUE THREAD

**Issue by DuYufengwin** [PocketNC/pocketnc#2]
I have run this code after git clone this repository :
`sudo ./enableServices.sh
./postUpdate.sh
`
However, startPocketNC.sh and startRockHopper.sh can not be run after rstart the beaglebone. 
Do you have any suggestions ?

**Comment by jakedanczyk** [comment]
Can you confirm you've followed the instructions given in the [README](https://github.com/PocketNC/pocketnc/blob/master/README.md)?

**Comment by DuYufengwin** [comment]
Yes I do follow the README...
| |
Yufeng Du
|
|
邮箱：dyfwin@yeah.net
|

Signature is customized by Netease Mail Master

On 03/19/2020 00:49, Jake Danczyk wrote:

Can you confirm you've followed the instructions given in the README?

**Comment by DuYufengwin** [comment]
I had run  `systemctl status PocketNC.service ` , and the print message as follow:
pocketnc@pocketnc:~/pocketnc$ systemctl status PocketNC.service 
● PocketNC.service - PocketNC Service
   Loaded: loaded (/home/pocketnc/pocketnc/PocketNC.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-03-14 06:21:21 UTC; 4 days ago
  Process: 1149 ExecStop=/home/pocketnc/pocketnc/stopPocketNC.sh (code=exited, status=0/SUCCESS)
  Process: 1108 ExecStart=/home/pocketnc/pocketnc/startPocketNC.sh (code=exited, status=127)
 Main PID: 1108 (code=exited, status=127)

Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]:   File "./generateINI.py", line 12, in <module>
Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]:     VERSION = getVersion()
Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]:   File "/home/pocketnc/pocketnc/Settings/version.py", line 63, in getVersion
Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]:     i2c = Adafruit_I2C(0x50)
Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]:   File "build/bdist.linux-armv7l/egg/Adafruit_I2C.py", line 17, in __init__
Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]: IOError: [Errno 13] Permission denied
Mar 14 06:21:20 pocketnc startPocketNC.sh[1108]: /home/pocketnc/pocketnc/startPocketNC.sh: line 17: linuxcnc: command not found
Mar 14 06:21:20 pocketnc systemd[1]: PocketNC.service: Main process exited, code=exited, status=127/n/a
Mar 14 06:21:21 pocketnc systemd[1]: PocketNC.service: Unit entered failed state.
Mar 14 06:21:21 pocketnc systemd[1]: PocketNC.service: Failed with result 'exit-code'.
